public class listOfWords {

   static String words[] = {"elephant", "jungle", "waterfall", "quicksilver", "volcano",
            "fantastic", "banana", "island", "chocolate", "zebra",
            "octopus", "giraffe", "noodle", "tiger", "umbrella",
            "apple", "happiness", "kangaroo", "magnificent", "rainbow",
            "strawberry", "xylophone", "lemonade", "pineapple",
            "the", "a", "an", "my", "your", "his", "her", "its", "our", "their",
            "I", "you", "he", "she", "it", "we", "they",
            "quickly", "slowly", "carefully", "always", "often", "very", "almost", "completely",
           "because", "turn", "here", "why", "asked", "went", "men", "read", "need", "land",
           "different", "home", "us", "move", "try", "kind", "hand", "picture", "again", "change",
           "off", "play", "spell", "air", "away", "animals", "house", "point", "page", "letters",
           "mother", "answer", "found", "study", "still", "learn", "should", "America", "world", "high",
           "near", "add", "food", "between", "own", "below", "country", "plant", "last", "school",
           "father", "keep", "tree", "never", "start", "city", "earth", "eye", "light", "thought",
           "head", "under", "story", "saw", "left", "don't", "few", "while", "along", "might",
           "close", "something", "seem", "next", "hard", "open", "example", "begin", "life", "always",
           "those", "both", "paper", "together", "got", "group", "often", "run", "important", "until",
           "children", "side", "feet", "car", "mile", "night", "walk", "white", "sea", "began", "grow",
           "took", "river", "four", "carry", "state", "once", "book", "hear", "stop", "without",
           "second", "late", "miss", "idea", "enough", "eat", "face", "watch", "far", "Indian", "real",
           "almost", "let", "above", "girl", "sometimes", "mountain", "cut", "young", "talk", "soon",
           "list", "song", "leave", "family", "it's", "body", "music", "color", "stand", "sun", "questions",
           "fish", "area", "mark", "dog", "horse", "birds", "problem", "complete", "room", "knew", "since",
           "ever", "piece", "told", "usually", "run", "better", "best", "however", "low", "hours", "black",
           "products", "happened", "whole", "measure", "remember", "early", "waves", "reached", "listen", "wind",
           "rock", "space", "covered", "fast", "several", "hold", "himself", "toward", "five", "step", "morning",
           "passed", "vowel", "true", "hundred", "against", "pattern", "numeral", "table", "north", "slowly", "money",
           "map", "farm", "pulled", "draw", "voice", "seen", "cold", "cried", "plan", "notice", "south", "sing",
           "war", "ground", "fall", "king", "town", "unit", "box", "run", "believe", "possible", "complete", "began",
           "someone", "river", "carry", "fall", "miss", "beyond", "cannot", "second", "government", "important", "morning",
           "system", "center", "island", "although", "continent", "understand", "equation", "determine", "weather", "reason", "exercise",
           "describe", "dictionary", "material", "length", "temperature", "community", "address", "language", "governor", "particle", "electricity",
           "discovery", "astronomy", "television", "environment", "department", "structure", "mathematics", "population", "university", "president", "information",
           "recognize", "government", "political", "experience", "throughout", "important", "opportunity", "particular", "significant", "technology", "management",
           "environment", "development", "environmental", "communication", "appropriate", "agriculture", "organization", "possibility", "determination", "environment", "responsibility",
           "understanding", "consideration"};
   }
